### ISSUE TITLE
Documentation not deployed

### ISSUE THREAD

**Issue by cserteGT3** [JuliaGizmos/Observables.jl#41]
I started to revisit the problems of deploying the documentation, when I realised, that it has been already done. Although it is still not working.
[Latest build](https://travis-ci.org/JuliaGizmos/Observables.jl/jobs/654656611#L308) shows a `Permission denied` error, and suggests that is may caused by a wrong `DOCUMENTER_KEY`.

Another problem could be, that every job tries to deploy the documentation. If all of them succeeds, there will be four (six?) identical copies of the same version?
Though I'm not sure that it is a real problem, the following travis script avoids this:
```
jobs:
   allow_failures:
     - julia: nightly
   include:
     - stage: Documentation
       julia: 1.0
       os: linux
       script:
         - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
         - julia --project=docs/ docs/make.jl
       after_success: skip
```
I can open a PR for the second, but can't fix or test the first.
